### ISSUE TITLE
"Using this component in your own app" does not work

### ISSUE THREAD

**Issue by Sebush** [christophebe/nice-suggest#2]
npm install nice-suggest -> done dir in node_modules exists... but

module.js:340
    throw err;
          ^
Error: Cannot find module 'nice-suggest'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/SOLUTE/sh/website/py_frontend/nodejs/seo/index.js:5:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by tomanagle** [comment]
Hi Sebus, this is quite obviously a bug. 

Change your require statement to:

`var suggest = require('nice-suggest/lib/suggest');'`
